env: flex
runtime: python
api_version: 1
threadsafe: false

runtime_config:
  python_version: 3

entrypoint: python3 app.py --port $PORT

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
